{{- if .Values.experimental.kubernetesGateway.enabled }}
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: traefik
spec:
  controllerName: traefik.io/gateway-controller
{{- end }}
